### ISSUE TITLE
Use a .env to define the COMPOSE_PROJECT_NAME env var

### ISSUE THREAD

**Issue by lebris** [Onyx-org/core#9]
instead of modifying the helper.mk file
 * https://github.com/Onyx-org/core/blob/master/wizards.mk#L27
 * https://github.com/Onyx-org/skeleton/blob/master/docker/helpers.mk

cf. https://docs.docker.com/compose/env-file/

**Comment by Niktux** [comment]
Fixed in https://github.com/Onyx-org/skeleton/pull/32
